/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://nzs6lhkbzzflvaf37gyt6kgd3u.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5nlvpzwb6zfrnawo2vhjfo6z7q",
    "aws_cognito_identity_pool_id": "us-east-1:fe4a855e-fb5e-481f-9caa-8ca6c143eeec",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_r7LSIcTjN",
    "aws_user_pools_web_client_id": "7scnr9ccno3egb2apbtq5vt7a3",
    "oauth": {},
    "aws_cognito_login_mechanism": [
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    }
};


export default awsmobile;
