import Head from "next/head";
import Link from "next/link";
import { API } from "aws-amplify";
import { listPosts } from "../graphql/queries";
import { useEffect, useState } from "react";
export default function Home() {
  const [posts, setPosts] = useState([]);

  useEffect(() => {
    fetchPosts();
  }, []);

  const fetchPosts = async () => {
    const postData = await API.graphql({
      query: listPosts,
    });
    setPosts(postData.data.listPosts.items);
    console.log(posts);
  };
  return (
    <div className="max-w-7xl mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1 className="text-3xl font-semibold tracking-wide mt-6 mb-2">
          Posts
        </h1>
        <div className="flex flex-col-reverse">
          {posts.length > 0 &&
            posts.map((post, idx) => (
              <Link href={`/posts/${post.id}`} key={idx} passHref>
                <div className="cursor-pointer border-b border-gray-300 mt-8 mb-4">
                  <p className="text-xl font-semibold">{post.title}</p>
                </div>
              </Link>
            ))}
        </div>
      </div>
    </div>
  );
}
